version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: CoursesCleanDB
    restart: always
    env_file:
      - .env.dev_credencials
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5431:5432"
