version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: CoursesCleanDB
    restart: always
    environment:
      POSTGRES_DB: CoursesClean
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
