spring:
  config:
    import: optional:file:.env.prod_credencials.proprieties.proprieties[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true